version: "3"
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
      - ./apache/drupaloracle.conf:/etc/apache/sites-enabled/drupaloracle.conf
      - ./html:/html
      - ./apache/certificados:/certificados
  basededatos:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - datosbd:/var/lib/mysql
      - ./db:/db
      - ./db/copias/:/docker-entrypoint-initdb.d
volumes:
  datosbd:
